MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "models/IC-13-15-17-Trial-angle-norm/model_0170000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 5.)
    DETECTIONS_PER_IMG: 300

DATALOADER:
  SIZE_DIVISIBILITY: 1

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 120000)
  MAX_ITER: 200000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/IC-13-15-17-Trial-angle-norm/'
