INPUT:
  MIN_SIZE_TRAIN: (800, 1000)
  MAX_SIZE_TRAIN: 1700
  ROTATION_RANGE: (60, 30)

MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_REC_HEAD:
    ALPHABET: "data_cache/alphabet_IC13_IC15_pro.txt"
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
  REC_ON: True


DATASETS:
  TRAIN: ("RRPN_E2E", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 160000)
  MAX_ITER: 200000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/IC-13-15-E2E/'
