MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "./models/ICDAR2019_ArT_baseline/model_0160000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 600
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
    DETECTIONS_PER_IMG: 300

TEST:
  DATASET_NAME: "ArT"
DATALOADER:
  SIZE_DIVISIBILITY: 1



