
MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "./models/ICDAR2019_LSVT_Trial_0.2_4_scales/model_0230000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    NMS: 0.2
    DETECTIONS_PER_IMG: 300
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)

  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (16,)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (4, 8, 16, 32)

TEST:
  DATASET_NAME: "LSVT"
DATALOADER:
  SIZE_DIVISIBILITY: 1

