INPUT:
  MIN_SIZE_TRAIN: (700, 800, 900, 1000)
  MAX_SIZE_TRAIN: 1700

MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 2.)

  RRPN:
    ASPECT_RATIOS: (0.125, 0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (16,)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (4, 8, 16, 32)

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 300000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/ICDAR2019_LSVT_Trial_0.2_4_scales_3_ratios_angle_norm/'
