INPUT:
  MIN_SIZE_TRAIN: (600, 800, 1000)
  MAX_SIZE_TRAIN: 1700

MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 120000)
  MAX_ITER: 160000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/ICDAR2019_ArT_baseline/'
