INPUT:
  MIN_SIZE_TRAIN: (800,1000)
  MAX_SIZE_TRAIN: 1700
  ROTATION_RANGE: (40, 20)

MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "models/IC15-full-E2E-FP4P-det-pretrain/model_0160000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FP4P"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_REC_HEAD:
    ALPHABET: "data_cache/alphabet_90Klex_IC13_IC15_Syn800K_pro.txt"
    POOLER_SCALES: (0.25, 0.125, 0.0625)
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    SCORE_THRESH: 0.0001
    NMS: 0.2
  REC_ON: True
  FP4P_ON: True
  RRPN:
    ASPECT_RATIOS: (0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (16,)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (4, 8, 16, 32)
DATALOADER:
  SIZE_DIVISIBILITY: 1
DATASETS:
  TRAIN: ("RRPN_E2E", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 250000)
  MAX_ITER: 400000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/IC15-full-E2E-FP4P-pretrain/'
